[window]
decorations = "Full"
opacity = 0.8
blur = true

[window.dimensions]
columns = 170
lines = 45

[window.padding]
x = 0
y = 0

[font]
size = 14

[font.bold]
family = "CaskaydiaCove NF"
style = "SemiBold"

[font.normal]
family = "CaskaydiaCove NF"
style = "Regular"

[colors.primary]
background = "0x0A0E14"
foreground = "0xB3B1AD"

[colors.normal]
black = "0x01060E"
blue = "0x53BDFA"
cyan = "0x90E1C6"
green = "0x91B362"
magenta = "0xFAE994"
red = "0xEA6C73"
white = "0xC7C7C7"
yellow = "0xF9AF4F"

[colors.bright]
black = "0x686868"
blue = "0x59C2FF"
cyan = "0x95E6CB"
green = "0xC2D94C"
magenta = "0xFFEE99"
red = "0xF07178"
white = "0xFFFFFF"
yellow = "0xFFB454"
